//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loan.Platform.Data.SqlServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loan.Platform.Data.SqlServer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;United States&quot;,&quot;Code&quot;:&quot;USA&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;2022-06-09T12:25:05.3266667&quot;,&quot;CreatedBy&quot;:1,&quot;ModifiedTime&quot;:&quot;2022-06-09T12:25:05.3266667&quot;,&quot;ModifiedBy&quot;:1,&quot;OrganizationId&quot;:1,&quot;TenantId&quot;:1},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Canada&quot;,&quot;Code&quot;:&quot;CAN&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;2022-06-09T12:25:05.3266667&quot;,&quot;CreatedBy&quot;:1,&quot;ModifiedTime&quot;:&quot;2022-06-09T12:25:05.3266667&quot;,&quot;ModifiedBy&quot;:1,&quot;OrganizationId&quot;:1,&quot;TenantId&quot;:1},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Mexico&quot;,&quot;Code&quot;:&quot;MEX&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;2022-06-09T12:25:05.3266667&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailConfigurations {
            get {
                return ResourceManager.GetString("MailConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;SignUpVerification&quot;,&quot;Description&quot;:&quot;Email Verification&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;2022-07-13T18:32:28.3490093&quot;,&quot;CreatedBy&quot;:1,&quot;ModifiedTime&quot;:&quot;2022-07-13T18:32:28.3490093&quot;,&quot;ModifiedBy&quot;:1,&quot;OrganizationId&quot;:0,&quot;TenantId&quot;:1},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;PasswordReset&quot;,&quot;Description&quot;:&quot;Reset Password&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;2022-07-13T18:32:28.3490093&quot;,&quot;CreatedBy&quot;:1,&quot;ModifiedTime&quot;:&quot;2022-07-13T18:32:28.3490093&quot;,&quot;ModifiedBy&quot;:1,&quot;OrganizationId&quot;:0,&quot;TenantId&quot;:1},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Rejected&quot;,&quot;Description&quot;:&quot;Acc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationEvents {
            get {
                return ResourceManager.GetString("NotificationEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;A-Equipped box cars&quot;,&quot;Description&quot;:&quot;Equipped box cars&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;0001-01-01T00:00:00&quot;,&quot;CreatedBy&quot;:0,&quot;ModifiedTime&quot;:&quot;0001-01-01T00:00:00&quot;,&quot;ModifiedBy&quot;:0,&quot;OrganizationId&quot;:0,&quot;TenantId&quot;:0},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;B-Unequipped box cars&quot;,&quot;Description&quot;:&quot;Unequipped box cars&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;0001-01-01T00:00:00&quot;,&quot;CreatedBy&quot;:0,&quot;ModifiedTime&quot;:&quot;0001-01-01T00:00:00&quot;,&quot;ModifiedBy&quot;:0,&quot;OrganizationId&quot;:0,&quot;TenantId&quot;:0},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;C-Covered hopper cars&quot;,&quot;Description&quot;:&quot;Covered h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RailcarTypes {
            get {
                return ResourceManager.GetString("RailcarTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: 1,
        ///    &quot;Name&quot;: &quot;US Central Region&quot;,
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;IsActive&quot;: true,
        ///    &quot;CreatedTime&quot;: &quot;2022-06-09T01:43:38.8133333&quot;,
        ///    &quot;CreatedBy&quot;: 1,
        ///    &quot;ModifiedTime&quot;: &quot;2022-06-09T01:43:38.8133333&quot;,
        ///    &quot;ModifiedBy&quot;: 1,
        ///    &quot;OrganizationId&quot;: 1,
        ///    &quot;TenantId&quot;: 1
        ///  },
        ///  {
        ///    &quot;Id&quot;: 2,
        ///    &quot;Name&quot;: &quot;US Midwest Region&quot;,
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;IsActive&quot;: true,
        ///    &quot;CreatedTime&quot;: &quot;2022-06-09T01:43:38.8133333&quot;,
        ///    &quot;CreatedBy&quot;: 1,
        ///    &quot;ModifiedTime&quot;: &quot;2022-06-09T01:43:38.81333 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Alabama&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;2022-06-09T15:13:05.8300000&quot;,&quot;CreatedBy&quot;:1,&quot;ModifiedTime&quot;:&quot;2022-06-09T15:13:05.8300000&quot;,&quot;ModifiedBy&quot;:1,&quot;OrganizationId&quot;:1,&quot;TenantId&quot;:1,&quot;Code&quot;:&quot;AL&quot;,&quot;CountryId&quot;:1},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Alaska&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;2022-06-09T15:13:05.8300000&quot;,&quot;CreatedBy&quot;:1,&quot;ModifiedTime&quot;:&quot;2022-06-09T15:13:05.8300000&quot;,&quot;ModifiedBy&quot;:1,&quot;OrganizationId&quot;:1,&quot;TenantId&quot;:1,&quot;Code&quot;:&quot;AK&quot;,&quot;CountryId&quot;:1},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Alberta&quot;,&quot;IsActive&quot;:true,&quot;CreatedTime&quot;:&quot;2022-06-09T15:13:05. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
    }
}
